-- AlterTable
ALTER TABLE `Order` ADD COLUMN `phone` VARCHAR(191) NOT NULL DEFAULT '0000000000',
    ADD COLUMN `shippingAddress` VARCHAR(191) NOT NULL DEFAULT 'Chưa cập nhật';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `address` VARCHAR(191) NOT NULL DEFAULT 'Chưa cập nhật',
    ADD COLUMN `phone` VARCHAR(191) NOT NULL DEFAULT '0000000000';
